### ISSUE TITLE
Installation exception

### ISSUE THREAD

**Issue by enderneko** [Sarjuuk/aowow#392]
Hi
Thanks for the great work!
but when execute `php aowow --setup`, this Exception has occurred.

php8.1, mysql8, latest 3.3.5 Trinity db.

```
02:44:17          SqlGen::generate() - filling aowow_spell with data
02:44:17           - reading spellradius.dbc
02:44:17           - reading spellduration.dbc
02:44:17           - reading spellrunecost.dbc
02:44:17           - reading spellcasttimes.dbc
02:44:17           - merging serverside spells into spell.dbc
02:44:47           - filling aowow_spell
02:53:45           - linking with skillineability
02:56:13           - linking with talent
02:56:13           - misc fixups & iconsException - Access to undeclared static property SpellList::$effects
   /var/www/aowow/setup/tools/sqlgen/spell.func.php(497)
#0 /var/www/aowow/setup/tools/sqlGen.class.php(239): SetupScript@anonymous->generate()
#1 /var/www/aowow/setup/tools/clisetup/setup.func.php(293): SqlGen::generate()
#2 /var/www/aowow/setup/setup.php(40): setup()
#3 /var/www/aowow/aowow(10): require('...')
#4 {main}
```

**Comment by Sarjuuk** [comment]
Hi, this was fixed in b2ca072120985946342c72e384ca1e0c6f03f4ae

you need to update.
